[{"exception":{"stacktrace":"openconnector.InvalidRequestException: [ InvalidRequestException ] \n [ Error details ] Request execution failed. HTTP Error code : 400, Okta Error code : E0000001, errorSummary : Api validation failed: login, errorCauses:[{errorSummary=login: An object with this field already exists in the current organization}].\n\tat openconnector.connector.okta.OktaConnector$OktaHttpClient.setResponseBody(OktaConnector.java:6548)\n\tat openconnector.connector.okta.OktaConnector$OktaHttpClient.fetchHttpResponse(OktaConnector.java:6261)\n\tat openconnector.connector.okta.OktaConnector.doRestRequest(OktaConnector.java:5915)\n\tat openconnector.connector.okta.OktaConnector.createAccount(OktaConnector.java:1445)\n\tat openconnector.connector.okta.OktaConnector.create(OktaConnector.java:828)\n\tat openconnector.AbstractConnector.provision(AbstractConnector.java:664)\n\tat sailpoint.connector.OpenConnectorAdapter.provision(OpenConnectorAdapter.java:999)\n\tat sailpoint.connector.ConnectorProxy.provision(ConnectorProxy.java:1116)\n\tat com.sailpoint.ccg.cloud.container.Container.provision(Container.java:310)\n\tat com.sailpoint.ccg.cloud.container.ContainerIntegration.provision(ContainerIntegration.java:156)\n\tat com.sailpoint.ccg.handler.ProvisionHandler.invoke(ProvisionHandler.java:190)\n\tat sailpoint.gateway.accessiq.CcgPipelineMessageHandler.handleMessage(CcgPipelineMessageHandler.java:26)\n\tat com.sailpoint.pipeline.server.PipelineServer$InboundQueueListener$MessageHandler.run(PipelineServer.java:369)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","exception_class":"openconnector.InvalidRequestException","exception_message":"[ InvalidRequestException ] \n [ Error details ] Request execution failed. HTTP Error code : 400, Okta Error code : E0000001, errorSummary : Api validation failed: login, errorCauses:[{errorSummary=login: An object with this field already exists in the current organization}]."},"stack":"ccg","pod":"stg01-useast1","connector-logging":"144","Operation":"Create","clusterId":"1467","buildNumber":"737","apiUsername":"32d86f12-ee16-48eb-8c7c-cc6da35f914e","ObjectType":"account","orgType":"development","file":"OktaConnector.java","encryption":"1266","messageType":"provision","connector-bundle-identityiq":"172","line_number":833,"@version":1,"CB_version":"535","logger_name":"openconnector.connector.okta.OktaConnector","mantis-client":"1266","class":"openconnector.connector.okta.OktaConnector","ParentOperation":"ProvisioningOperation","clientId":"4575","request_milliseconds":"3783","source_host":"c3ec057d0168","method":"create","org":"inspirebrands-sb","level":"ERROR","IdentityIQ":"8.0 Build 2f61d76cf47-20220429-140148","message":"Failed to create the account. ","pipeline":"1266","@timestamp":"2022-08-09T04:47:44.321Z","NativeIdentity":"70000054","thread_name":"pool-5-thread-1","metrics":"1266","region":"us-east-1","AppType":"Okta","Application":"Okta [source]","request_id":"8e60f60b7f4f4768b5df3d29f4ee1e0f","CB_Type":"connector-bundle-webservices","queue":"stg01-useast1-inspirebrands-sb-cluster-1467","SCIM Common":"8.0 Build 00b1f252d1b-20200225-190809"}]